//! MCNP 领域模型。
//!
//! 本 crate 只保存跨 Core、Panel 和客户端共享的值对象、状态机和能力画像。
//! 网络传输、文件系统和数据库实现不得反向改变这些领域约束；尤其是
//! `InstanceKind`、`ProxyTopology` 和 `BedrockManagementProfile` 共同决定
//! 服务端类型应使用哪套运维逻辑。

mod bedrock_bind_address_source;
mod bedrock_health;
mod bedrock_health_status;
mod bedrock_management_kind;
mod bedrock_management_profile;
mod bedrock_port_check;
mod bedrock_port_check_state;
mod bedrock_port_source;
mod bedrock_transport;
mod core_id;
mod cpu_availability;
mod cpu_logical_processor;
mod cpu_performance_class;
mod cpu_policy;
mod cpu_policy_error;
mod cpu_policy_mode;
mod cpu_share_mode;
mod cpu_topology;
mod cpu_topology_detection;
mod download_architecture;
mod download_manifest;
mod download_platform;
mod event_id;
mod extension_artifact;
mod extension_compatibility;
mod extension_dependency;
mod extension_install;
mod extension_install_request;
mod extension_kind;
mod extension_plan_item;
mod extension_plan_request;
mod extension_plan_resolution;
mod extension_project;
mod extension_search_result;
mod extension_version;
mod extension_version_result;
mod file_content;
mod file_entry;
mod file_kind;
mod file_page;
mod install_runtime_requirement;
mod install_template;
mod install_template_extension_layout;
mod install_template_family;
mod install_template_version;
mod install_template_version_kind;
mod instance;
mod instance_create;
mod instance_create_error;
mod instance_id;
mod instance_id_error;
mod instance_kind;
mod instance_log_line;
mod instance_log_page;
mod instance_log_stream;
mod instance_metric_sample;
mod instance_page;
mod instance_runtime;
mod instance_state;
mod instance_update;
mod instance_update_error;
mod launch_config;
mod managed_runtime;
mod mcdr_config;
mod patch_field;
mod provision_plan;
mod proxy_subserver;
mod proxy_subserver_error;
mod proxy_subserver_health;
mod proxy_subserver_health_status;
mod proxy_subserver_protocol_status;
mod proxy_topology;
mod request_id;
mod runtime_archive_format;
mod runtime_install_manifest;
mod runtime_kind;
mod runtime_mode;
mod runtime_source;
mod runtime_validation;
mod sha256_digest;
mod sha256_digest_error;
mod supervisor_mode;
mod task_id;
mod version_metadata_provider;

pub use bedrock_bind_address_source::BedrockBindAddressSource;
pub use bedrock_health::BedrockHealth;
pub use bedrock_health_status::BedrockHealthStatus;
pub use bedrock_management_kind::BedrockManagementKind;
pub use bedrock_management_profile::BedrockManagementProfile;
pub use bedrock_port_check::BedrockPortCheck;
pub use bedrock_port_check_state::BedrockPortCheckState;
pub use bedrock_port_source::BedrockPortSource;
pub use bedrock_transport::BedrockTransport;
pub use core_id::CoreId;
pub use cpu_availability::CpuAvailability;
pub use cpu_logical_processor::CpuLogicalProcessor;
pub use cpu_performance_class::CpuPerformanceClass;
pub use cpu_policy::CpuPolicy;
pub use cpu_policy_error::CpuPolicyError;
pub use cpu_policy_mode::CpuPolicyMode;
pub use cpu_share_mode::CpuShareMode;
pub use cpu_topology::CpuTopology;
pub use cpu_topology_detection::CpuTopologyDetection;
pub use download_architecture::DownloadArchitecture;
pub use download_manifest::DownloadManifest;
pub use download_platform::DownloadPlatform;
pub use event_id::EventId;
pub use extension_artifact::ExtensionArtifact;
pub use extension_compatibility::ExtensionCompatibility;
pub use extension_dependency::ExtensionDependency;
pub use extension_install::ExtensionInstall;
pub use extension_install_request::ExtensionInstallRequest;
pub use extension_kind::ExtensionKind;
pub use extension_plan_item::ExtensionPlanItem;
pub use extension_plan_request::ExtensionPlanRequest;
pub use extension_plan_resolution::ExtensionPlanResolution;
pub use extension_project::ExtensionProject;
pub use extension_search_result::ExtensionSearchResult;
pub use extension_version::ExtensionVersion;
pub use extension_version_result::ExtensionVersionResult;
pub use file_content::FileContent;
pub use file_entry::FileEntry;
pub use file_kind::FileKind;
pub use file_page::FilePage;
pub use install_runtime_requirement::InstallRuntimeRequirement;
pub use install_template::InstallTemplate;
pub use install_template_extension_layout::InstallTemplateExtensionLayout;
pub use install_template_family::InstallTemplateFamily;
pub use install_template_version::InstallTemplateVersion;
pub use install_template_version_kind::InstallTemplateVersionKind;
pub use instance::Instance;
pub use instance_create::InstanceCreate;
pub use instance_create_error::InstanceCreateError;
pub use instance_id::InstanceId;
pub use instance_id_error::InstanceIdError;
pub use instance_kind::InstanceKind;
pub use instance_log_line::InstanceLogLine;
pub use instance_log_page::InstanceLogPage;
pub use instance_log_stream::InstanceLogStream;
pub use instance_metric_sample::InstanceMetricSample;
pub use instance_page::InstancePage;
pub use instance_runtime::InstanceRuntime;
pub use instance_state::InstanceState;
pub use instance_update::InstanceUpdate;
pub use instance_update_error::InstanceUpdateError;
pub use launch_config::LaunchConfig;
pub use managed_runtime::ManagedRuntime;
pub use mcdr_config::McdrConfig;
pub use patch_field::PatchField;
pub use provision_plan::ProvisionPlan;
pub use proxy_subserver::ProxySubserver;
pub use proxy_subserver_error::ProxySubserverError;
pub use proxy_subserver_health::ProxySubserverHealth;
pub use proxy_subserver_health_status::ProxySubserverHealthStatus;
pub use proxy_subserver_protocol_status::ProxySubserverProtocolStatus;
pub use proxy_topology::ProxyTopology;
pub use request_id::RequestId;
pub use runtime_archive_format::RuntimeArchiveFormat;
pub use runtime_install_manifest::RuntimeInstallManifest;
pub use runtime_kind::RuntimeKind;
pub use runtime_mode::RuntimeMode;
pub use runtime_source::RuntimeSource;
pub use runtime_validation::RuntimeValidation;
pub use sha256_digest::Sha256Digest;
pub use sha256_digest_error::Sha256DigestError;
pub use supervisor_mode::SupervisorMode;
pub use task_id::TaskId;
pub use version_metadata_provider::VersionMetadataProvider;

/// Web API 的主版本号。
pub const API_VERSION: &str = "v1";
/// 产品展示名。
pub const PRODUCT_NAME: &str = "MCNP";
/// 从 Cargo 包元数据读取的产品版本。
pub const PRODUCT_VERSION: &str = env!("CARGO_PKG_VERSION");
