[package]
name = "mcnp-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "mcnp_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
tauri.workspace = true

[lints]
workspace = true
