[package]
name = "mcnp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
nexus-config.workspace = true
nexus-core.workspace = true
nexus-domain.workspace = true
nexus-panel.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
